### ISSUE TITLE
crash if can't obtain connection with cablecast server

### ISSUE THREAD

**Issue by patdunlavey** [raytiley/Cablecast-Drupal-Module#1]
[08-Sep-2010 00:04:45] PHP Fatal error:  Uncaught SoapFault exception: [HTTP] Could not connect to host in /Applications/MAMP/localhost htdocs/willinet-drupal/sites/all/modules/Cablecast-Drupal-Module.git/cablecast.module:273
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://137.165....', 'http://www.trms...', 1, 0)
#1 [internal function]: SoapClient->__call('GetChannels', Array)
#2 /Applications/MAMP/localhost htdocs/willinet-drupal/sites/all/modules/Cablecast-Drupal-Module.git/cablecast.module(273): SoapClient->GetChannels(NULL)
#3 /Applications/MAMP/localhost htdocs/willinet-drupal/sites/all/modules/Cablecast-Drupal-Module.git/cablecast.module(69): cablecast_sync_channels(Object(SoapClient))
#4 [internal function]: cablecast_cron()
#5 /Applications/MAMP/localhost htdocs/willinet-drupal/includes/module.inc(483): call_user_func_array('cablecast_cron', Array)
#6 /Applications/MAMP/localhost htdocs/willinet-drupal/includes/common.inc(2744): module_invoke_all('cron')
#7 /Applications/MAMP/localhost htdocs/willi in /Applications/MAMP/localhost htdocs/willinet-drupal/sites/all/modules/Cablecast-Drupal-Module.git/cablecast.module on line 273

**Comment by patdunlavey** [comment]
I used this in my earlier incarnation:
<?php
      try {
        $this->client = new SoapClient($this->server_url);  //Creates New SOAP client using WSDL file
        // See if cablecast client is real by calling it
        // need a way to test that we have connectivity to Cablecast without throwing
        // a PHP or SOAP error if we can't connect. Using try - catch allows it to fail gracefully
        // (but still shows warning messages).
        // .... call WSVersion() to cause a failure when there is no connection
        $this->client->WSVersion();
        return TRUE;
      } catch (SoapFault $fault) {
        //        print("Sorry, Cablecast returned the following error: ".$fault->faultstring);
        unset($this->client);
        return FALSE;
      }
?>

**Comment by raytiley** [comment]
Pat,

Good catch.  I haven't really done much in the way of error checking yet.  I've pulled in your changes.   I'm going to start making some bigger changes, but like what you've done so I figure this will make the merge later a bit easier.

**Comment by raytiley** [comment]
So I moved the WSVersion check to its own method that actually validates the Version.  Cron doesn't continue if the WSVersion is not high enough.  Also all three of the sync methods (projects, channels, shows)  are wrapped it try blocks which catch soap faults just incase there is some weird server hiccup.

You should probably fetch upstream so your working off these changes as well.  

first thing tomorrow morning I'll go over the DB schema and lock that in.

**Comment by patdunlavey** [comment]
I fetch upstream. Regarding DB schema, a change I'd like to see is the addition of producer name to cablecast_show. I understand you plan to use Drupal users to store producer info, and I think that's great. But I'd like to not have to necessarily rely upon that just to be able to display the Producer's name with Show info. I added this to my version of cablecast.install (though I haven't made the corresponding changes in the module file).
