### ISSUE TITLE
EDIT Cablecast Show

### ISSUE THREAD

**Issue by nrollins** [raytiley/Cablecast-Drupal-Module#10]
When I try to edit a cablecast show I cannot save changed it is requiring fields that have no data and I cannot enter the data.

Description: *
DSK Bug Text: *
DSK Crawl Text: *

With no data I cannot save changes nor enter the data into the field.

**Comment by raytiley** [comment]
Hey Nathan,

Yeah. I saw that error the other day too.  I have a fix.  I'll push it up in a little bit.

**Comment by raytiley** [comment]
Fixed Permissions in Cablecast_Show Form.  Closed by 7636b79c4997ed6273a14971a6e44df75b89dd8f
