### ISSUE TITLE
saving cablecast project node sets project_id to 0

### ISSUE THREAD

**Issue by patdunlavey** [raytiley/Cablecast-Drupal-Module#11]
View a cablecast project node, click edit, change nothing, save. The cablecast_project_id field is set to zero!

**Comment by raytiley** [comment]
Thats no good.  Looking into it

**Comment by raytiley** [comment]
Hey Pat, Checkout my latest commit.  Should fix your issue.

**Comment by raytiley** [comment]
I think this issue is fixed.  Closing it.
