### ISSUE TITLE
Cablecast Progect View

### ISSUE THREAD

**Issue by nrollins** [raytiley/Cablecast-Drupal-Module#14]
Ray

Is there a way to have a new view for cablecast Projects and then filter by project for display. Example a page for all cablecast project government videos that displays the name of the government as in cablecast when you create a project then take you to a list of mtgs. We also have a player in our theme that pulls the stram and plays the file.

**Comment by raytiley** [comment]
@nrollins sorry for never responding... it's easy to miss github issues, so please @mention me if you don't get a timely response.
