### ISSUE TITLE
cablecast_media_node_presave failing

### ISSUE THREAD

**Issue by joetri** [raytiley/Cablecast-Drupal-Module#15]
Ray,
I dropped in the recent code. It did create ONE new image file in sites/default/files/cablecast and then coughed with the following:

> Notice: Undefined index: und in cablecast_media_node_presave() (line 9 of /var/www/dev3/sites/all/modules/cablecast_media/cablecast_media.module).

I'll take at this tomorrow.

**Comment by raytiley** [comment]
@joetri are you using the `Local` module?

EDIT: I mean the `Locale` module. Its complaining that `und` doesn't exist, which is the normal thing. But I guess if your using `Locale` its better practice to use `$node->language` when indexing the fields.

**Comment by joetri** [comment]
"Locale" module not enabled presently or ever on this install.

I've seen similar issues before. Possibly like https://api.drupal.org/api/drupal/includes!bootstrap.inc/constant/LANGUAGE_NONE/7

I'll dump out the $node->cablecast_show_thumbnail and look at the structure.

**Comment by joetri** [comment]
See attached. 'und' is definitely the index _after_ node creation. Is it possible that the node structure is different when this hook is called at the presave state?
![s](https://cloud.githubusercontent.com/assets/2521452/11506136/d663f5f8-981b-11e5-975d-8f105c68acd5.png)

**Comment by joetri** [comment]
I am seeing that sometimes the system is storing the thumbnail structure with detail only down to 

> $node->cablecast_show_thumbnail['und']

and so your

> isset($node->cablecast_show_thumbnail)

should be 

> isset($node->cablecast_show_thumbnail['und'][0]['fid'])

since this is the fully expanded object with all detail that you compare to.

This modification is working for me when editing a cablecast show.

**Comment by raytiley** [comment]
I would think `isset($node->cablecast_show_thumbnail['und'][0]['fid'])` would throw an exception because your trying to index a potentially undefined field. If anything I would think it should be

``` php
if (isset($node->cablecast_show_thumbnail) &&
    isset($node->cablecast_show_thumbnail['und']) &&
    isset($node->cablecast_show_thumbnail['und'][0]))
```

which seems extremely verbose and crazy. What's annoying is this is working perfectly fine on my system, but I haven't had a chance to test a fresh install, so it might be something that changed in an update of `media` or event `drupal` itself.

**Comment by joetri** [comment]
Perhaps we're looking for 'defined'? You may be right on the module version changes. My code works for my install. I think there's also a different state on initial install vs use on an up and running system post module install. My module versions attached for what it's worth.
[list.txt](https://github.com/raytiley/Cablecast-Drupal-Module/files/49837/list.txt)

**Comment by raytiley** [comment]
Closing due to in activity... please re-open if an issue in recent code.
