### ISSUE TITLE
How do I implement the 6.0 thumbnail fix?

### ISSUE THREAD

**Issue by esue1943** [raytiley/Cablecast-Drupal-Module#17]
Ray,
I put the new cable cast media module on my site. No matter how many times I update the site, it picks up some but not all of the missing thumbnails. I tried deleting the Cablecast show media associated with the missing thumbnail and it doesn't pick that show back up. What do I do?

**Comment by raytiley** [comment]
If you install the latest code it's going to do a full sync. That will take some time.

Also Cablecast 6.0.x uses new thumbnail APIs which is great that Cablecast actually really supports thumbnails now :tada:, before the module was just guessing where a thumbnail might be and pulling it down.

if you send me an email raytiley@gmail.com with the public URL for your cablecast system I can do a quick test and see if I'm seeing any weird results. The new code _should_ work, but I haven't tested very thoroughly. Please include what show ids aren't pulling over thumbnails as you would expect.

**Comment by esue1943** [comment]
Ray,

I haven’t pushed the changes to the live site yet. I’ve done some testing on my local site with odd results. I put the new module in and run cron a bunch of times. It picks up some of the missing thumbnails but not all of them no matter how many times I try to update it. I tried deleting one of the show records thinking that it would restore it and the thumbnail but it never restores it. I have finally given up and have starting doing a fresh build of the site. That seems to work fine. I have a testing site I can push the code to and you can take a look at it there. I’ll let you know when I do it.

Are the new api changes backward compatible to non 6.x versions of Cablecast? Do you need to start a separate fork for sites that haven’t upgraded to 6.x? I don’t see us upgrading to 6.x anytime soon because the interface is so different and we would need to do a lot of retraining with our staff that doesn’t like changes.

Dick
