### ISSUE TITLE
Cron syncing shows fails to update category field

### ISSUE THREAD

**Issue by esue1943** [raytiley/Cablecast-Drupal-Module#18]
I have a lot of shows that were originally filed in the wrong category. If I go into cablecast and update the category to the correct one and then run cron it sees a change was made to the show but doesn't actually update the category field. Do you have a fix for this?

**Comment by raytiley** [comment]
@esue1943 sorry I didn't notice this email come in almost a year ago 😢 

Can you try the latest code on the `7.x-3.x` that I just pushed? Let me know if your still having issues.... I have more people using this module suddenly, so will try to take care of any issues :)
