### ISSUE TITLE
error when entering cablecast server url

### ISSUE THREAD

**Issue by natem1414** [raytiley/Cablecast-Drupal-Module#19]
Fatal error: Class 'SoapClient' not found in /home/mtn/public_html/sites/all/modules/Cablecast-Drupal-Module-7.x-1.x/cablecast/cablecast.module on line 86

Also throws error out when running cron

**Comment by raytiley** [comment]
`SoapClient` is a php class. Sounds like your version of php doesn't have it enabled?

http://php.net/manual/en/class.soapclient.php
