### ISSUE TITLE
Tightrope Update for Case #78424 - "VOD file processing and displaylay"

### ISSUE THREAD

**Issue by esue1943** [raytiley/Cablecast-Drupal-Module#20]
Ray,
I'm using the latest code you have here with Cablecast 6.1.3 Build 13. I sometimes encounter this problem where the VOD Url comes thru as http://74.92.17.125/VOD/ without the file name. All the information in cablecast is good but I get this broken Url and it never updates correctly. This is kind of like what I pointed out last year that if I updated the show category in cablecast the record in the drupal database never gets updated. I don't know what you are looking at in cablecast to see if something needs to be updated but it seems to fail sometimes. Could you please check this out so I can make my customer happy?

Dick

**Comment by raytiley** [comment]
Hey Dick... Try using the 3.x branch I just pushed up. I fixed this a while back. The issue is that the module wasn't testing the VOD record to make sure it was in a completed stage.

https://github.com/raytiley/Cablecast-Drupal-Module/commit/2d62cad878092feaf45daf7c703d66e553b43167
