### ISSUE TITLE
use of time() can produce incorrect results when pruning schedule events

### ISSUE THREAD

**Issue by patdunlavey** [raytiley/Cablecast-Drupal-Module#4]
In my fork, I added a function called _cablecast_site_time() that compares the server's timezone offset to the drupal site's, and offsets the value of time() by that amount.

**Comment by patdunlavey** [comment]
pretty picky, I know, but for example, if your server is three timezones away, you could find your schedule events for today disappearing after 9pm! 
Actually, I wonder if it makes more sense to just offset the FromDate about one day into the past? Is there a reason that past schedule events must immediately be purged?

**Comment by raytiley** [comment]
Hmmm

The way its working now (or at least should be working) is that it grabs all future events from cablecast, and drupal.  Goes through all the events in cablecast and updates them (no way to determine weather they have changed or not) and removes them from the array of schedule events in drupal.

Whats left in that schedule array is presumably deleted in cablecast, and therefore is deleted in drupal.

The offset could work, but then it doesn't account for the fact that the servers may be wildly out of sync with each other, even if the timezone factor is taken into account.  

Its probably better just to load 10 hours in the past for both cablecast and drupal, and keep the logic the same.

**Comment by patdunlavey** [comment]
I could be mistaken, of course. I ran into the cablecast timestamp vs. Drupal host server's timestamp problem in the earler stuff I was doing, and this solution fixed it. Since cablecast necessarily keeps track of local, real-world time, if the drupal host is not operating in the same time zone, it seems self-evident that will result in a misunderstanding about when "now" (time()) is. It is possible to get the drupal host's offset from GMT, and to get the drupal instance's offset (assuming the site drupal admin set it). So I do think it's knowable with some confidence.
Anyway, I agree that going a several hours back in time for the schedule event "don't prune yet" threshold makes sense.

**Comment by raytiley** [comment]
Pat, I pulled in your changes.  I'm still going to set the schedule sync to look ten hours in the past.

**Comment by patdunlavey** [comment]
closed
