### ISSUE TITLE
VOD Playback

### ISSUE THREAD

**Issue by nrollins** [raytiley/Cablecast-Drupal-Module#7]
Ray

Would it be possible to get this working with the JW Player like the older stuff you created.

**Comment by raytiley** [comment]
Nathan,

All the data will be available to do exactly what you did in your older stuff.  It wouldn't be something I would bake into the module cause it would add some weird dependencies.  Most likely you would just add the player files and stuff to your theme layer.

-ray

**Comment by raytiley** [comment]
I'm closing this since I believe Nathan figured out how to put the jwplayer stuff in his theme layer.  Actually embeding the streaming_file_url from cablecast will never be done in this module.  Too many dependencies for not enough users.
