### ISSUE TITLE
Should I make jquery_ui a requirement

### ISSUE THREAD

**Issue by raytiley** [raytiley/Cablecast-Drupal-Module#8]
In my local branch I've created a template file for cablecast schedule and moved the generation of the schedule into a preprocess function.  Both the function and the template file could be overridden by drupal themers.  For the default template I want to include a datepicker so that out of the box it is easy to navigate through the schedule.

The best way I see of doing this so far is by adding a dependency on the jquery_ui module.

http://drupal.org/project/jquery_ui

Anyone have any objections to such a dependency.  I already use it on my site, and I feel its probably pretty common.

**Comment by raytiley** [comment]
I just pushed the initial work.  You can see it here:

https://github.com/raytiley/Cablecast-Drupal-Module/commit/72034b7f68bb0c1b293386507d20d94fcd63fff1

I kinda really like this approach.  Even though it requires an additional module, it means that site builders don't need to set up complicated views just to get a basic schedule working.

**Comment by patdunlavey** [comment]
I have no problem with requiring jquery_ui. It's nearly ubiquitous.
I used the Date module's datepicker implementation myself, with a form and form_submit function (see http://willinet.patdunlavey.com/schedule). 
Took me a bit to understand how you're using the script in the template file to get the datepicker selection into the schedule_page function - very clever! I think I'll stick with my approach though, which allows date and channel to be selected before the page reloads.
I'm not sure why you are using a template_preprocess function to construct the table. Shouldn't the template do that? As you can see, I have another column for the link to the online video, which I add in a preprocess function. The table itself gets built in a template file.

**Comment by raytiley** [comment]
Pat,

Your schedule looks awesome!  Is that actually using the earlier implementation of my schedule page, or is that all views?

This is my first attempt at putting theming things in a module.  To be honest its been a bit of trial and error.  It makes sense that building the table should go into the template file itself.  I'll make that change.  I wanted to add a few other things to the template as well, also make that javascript a bit smarter so that it highlights the current day.

The goal here is to make the Cablecast Module give you the absolute basics (Shows and a Schedule) in a fairly presentable way that doesn't need a lot of custom theming just to get working.  I think I'm pretty close to that with the schedule aspect.  There is no views magic or really special modules besides jquery_ui.  My next step is to do the same with shows and projects.

I've started a demo site at http://cablecast.raytiley.com   The username is 'admin' and password is 'trms'  My goal is to use that site in a serious of screencasts to show how a TV stations site can be setup with the cablecast module.  You can see if you look at the installed modules that the only add on modules so far are:

jquery_update
jquery_ui
admin_menu
cablecast

Thanks again for all your help.

-ray

**Comment by patdunlavey** [comment]
I did my schedule page in a separate module which freely copied from your earlier implementation. I haven't figured out how to do views.
I'm impressed and very grateful for your efforts to make this module provide basic functionality in a way that works out of the box with few requirements, yet is as extendable as anyone might want. I'd still be on square-one without your work! Each time you update the repo, I go "oh, that's way better than the way I tried to do that!" It's all a very good learning experience for me!
I love your idea of doing a series of screencasts. There is not nearly enough of that sort of thing: domain-specific how-to's.
One comment: Is there a risk to publishing the admin login for the demo site here?

**Comment by raytiley** [comment]
I'm glad people are using my work :)

I'm sure the admin login will get scraped eventually, but I was going to publish it in my screencasts anyway.  Once I do the screencasts I'm going to take a snapshot of the DB and refresh it every 12 hours or 24 hours so that people can login as admin and really mess around w/ the module.

-ray

**Comment by raytiley** [comment]
So this is implemented and working really well.

-ray
